"""Trace the Aboveboard Group logo into one vector path per shape, for the header, footer and preloader.

No vector logo is published. The sharpest copy is the 2000 x 2000 JPG the live homepage uses as its "About" image
(the full logo on black). Each brand colour is masked separately and traced by vtracer in binary mode, then every
path is named by its position: the mark (flame, hook, bowl, wave) and the wordmark (ABOVEBOARD, GROUP, per letter).
Output: lib/logo-parts.ts. Needs Pillow + vtracer. Run: python3 scripts/trace_logo.py
"""
import os
import re
import urllib.request

import vtracer
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, "_recon")
SRC = "https://storage.readdy-site.link/project_files/9435a312-c7db-4fa3-8712-dd64feb0a3c0/f3ca970a-5393-459e-9cc2-7c86cf7a9c2e_aboveboard_group_higher_quality.jpg?v=15d5c10c02ad7d0887a0c7969e722375"
os.makedirs(WORK, exist_ok=True)
jpg = os.path.join(WORK, "logo-hq.jpg")
if not os.path.exists(jpg):
    urllib.request.urlretrieve(SRC, jpg)

im = Image.open(jpg).convert("RGB")
px, (w, h) = im.load(), im.size
masks = {  # thresholds picked from the pixel histogram: amber #fab52b, blue #2575b3, white wordmark
    "amber": lambda r, g, b: r > 150 and g > 90 and b < 120 and r - b > 90,
    "blue": lambda r, g, b: b > 110 and b - r > 60,
    "white": lambda r, g, b: r > 150 and g > 150 and b > 150 and abs(r - b) < 40,
}

parts = []
for tone, test in masks.items():
    m = Image.new("L", (w, h), 255)
    mp = m.load()
    for y in range(h):
        for x in range(w):
            if test(*px[x, y]):
                mp[x, y] = 0
    png, svg = os.path.join(WORK, f"mask-{tone}.png"), os.path.join(WORK, f"trace-{tone}.svg")
    m.convert("RGB").save(png)
    vtracer.convert_image_to_svg_py(png, svg, colormode="binary", filter_speckle=24, corner_threshold=60,
                                    length_threshold=4.0, splice_threshold=45, path_precision=2, mode="spline")
    for d, tx, ty in re.findall(r'<path d="([^"]+)"[^>]*transform="translate\(([\d.-]+),([\d.-]+)\)"', open(svg).read()):
        nums = [float(n) for n in re.findall(r"-?\d+(?:\.\d+)?", d)]
        xs, ys = nums[0::2], nums[1::2]
        tx, ty = float(tx), float(ty)
        parts.append({"tone": tone, "d": d, "x": round(tx, 2), "y": round(ty, 2),
                      "box": (tx + min(xs), ty + min(ys), tx + max(xs), ty + max(ys))})

# Name the parts. Mark: the tallest amber shape is the flame, the lowest the bowl, the small one the hook.
amber = sorted((p for p in parts if p["tone"] == "amber"), key=lambda p: p["box"][3] - p["box"][1], reverse=True)
flame, rest = amber[0], amber[1:]
bowl = max(rest, key=lambda p: p["box"][3])
hook = [p for p in rest if p is not bowl][0]
flame["id"], bowl["id"], hook["id"] = "flame", "bowl", "hook"
next(p for p in parts if p["tone"] == "blue")["id"] = "wave"
white = [p for p in parts if p["tone"] == "white"]
top = sorted((p for p in white if p["box"][1] < 1400), key=lambda p: p["box"][0])
low = sorted((p for p in white if p["box"][1] >= 1400), key=lambda p: p["box"][0])
for i, (p, ch) in enumerate(zip(top, "ABOVEBOARD")):
    p["id"] = f"w{i}-{ch}"
for i, (p, ch) in enumerate(zip(low, "GROUP")):
    p["id"] = f"g{i}-{ch}"

def bounds(items):
    return (min(p["box"][0] for p in items) - 8, min(p["box"][1] for p in items) - 8,
            max(p["box"][2] for p in items) + 8, max(p["box"][3] for p in items) + 8)

x0, y0, x1, y1 = bounds(parts)
mx0, my0, mx1, my1 = bounds([p for p in parts if p["tone"] != "white"])

order = ["flame", "hook", "bowl", "wave"] + [p["id"] for p in top] + [p["id"] for p in low]
by_id = {p["id"]: p for p in parts}
lines = [
    "// Generated by scripts/trace_logo.py from the 2000px logo JPG on aboveboardgroup.co.uk. Do not edit by hand.",
    "// Each part is one traced shape. x/y is the path's own translate(), kept on a wrapping <g> so GSAP can transform the path.",
    'export type LogoPart = { id: string; group: "mark" | "word" | "group"; tone: "amber" | "blue" | "white"; x: number; y: number; d: string };',
    f'export const LOGO_VIEWBOX = "{x0:.0f} {y0:.0f} {x1 - x0:.0f} {y1 - y0:.0f}";',
    f'export const MARK_VIEWBOX = "{mx0:.0f} {my0:.0f} {mx1 - mx0:.0f} {my1 - my0:.0f}";',
    "export const logoParts: LogoPart[] = [",
]
for pid in order:
    p = by_id[pid]
    group = "mark" if p["tone"] != "white" else ("word" if pid.startswith("w") else "group")
    lines.append(f'  {{ id: "{pid}", group: "{group}", tone: "{p["tone"]}", x: {p["x"]}, y: {p["y"]}, d: "{p["d"]}" }},')
lines.append("];")
open(os.path.join(ROOT, "lib", "logo-parts.ts"), "w").write("\n".join(lines) + "\n")
print(len(order), "parts; logo", f"{x0:.0f} {y0:.0f} {x1 - x0:.0f} {y1 - y0:.0f}", "mark", f"{mx0:.0f} {my0:.0f} {mx1 - mx0:.0f} {my1 - my0:.0f}")
for pid in order:
    print(pid, [round(v) for v in by_id[pid]["box"]])
